# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - documentai-bki-webapp-dev

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://aispaces.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d3d50aa0c7694ee4b832eb36b92f0d0a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ecc57bdd804d4fe9b90889f6babc848d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aispaces.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3d50aa0c7694ee4b832eb36b92f0d0a }}/staging:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'documentai-bki-webapp-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6c6b89784f01469f87496a271821d2ea }}
        images: 'aispaces.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3d50aa0c7694ee4b832eb36b92f0d0a }}/staging:${{ github.sha }}'